spring.h2.console.enabled: true
logging.level.org.hibernate.SQL: debug


---
server:
  port: 8080
  contextPath: /full-stack
---

datasource:
  disneyApp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxIdle: 10
    minIdle: 5
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
